# === CONFIGURATION CONSTANTS ===
SHEET_ID = "1JsWQDnxHis79dHcdlZZlgO1HS5Ldlq8zvLD1FdEwBQ4"
EXTERNAL_SHEET_ID = "193QJBSQKkW1-c2Z3WHv3o2rbX-zZwn9fnmEACj88cEw"


# === New runtime and start delay constants ===
MAX_RAW_BATCH_SIZE = 20
MAX_RUN_COUNT_FOR_PRIORITY = 3
SYNC_INTERVAL_SECONDS = 10
MAX_RUNTIME_HOURS = 5.25
EARLY_WINDOW_RUNNING_BUFFER = 1.0
INTERVAL_SECONDS = 10
DURATION_MINUTES = MAX_RUNTIME_HOURS * 60  # hours divided into minutes
FLOOR_END_BUFFER = 15

# === Sheet Names ===
CURRENT_SHEET = "Current"
PRIORITY_SHEET = "Priority"
NON_PRIORITY_SHEET = "NonPriority"
REPORTS_SHEET = "Reports"
REJECTED_SHEET = "RejectedSubmissions"

# Status text
STATUS_NOT_ACTIVE = "Floor Trials - Not Active"
STATUS_IN_PROGRESS = "Floor Trials - In Progress"
STATUS_OPEN = "Floor Trials - Open for Check-in"

# Ranges
CURRENT_QUEUE_RANGE = "Current!E6:I12"
PRIORITY_QUEUE_RANGE = "Priority!B3:F"
NON_PRIORITY_QUEUE_RANGE = "NonPriority!B3:F"
REPORTS_RANGE = "Reports!A4:E"
REJECTED_RANGE = "RejectedSubmissions!B4:H"

# Time-related ranges
FLOOR_OPEN_RANGE = "Current!B15"
FLOOR_START_RANGE = "Current!B16"
FLOOR_END_RANGE = "Current!B17"
FLOOR_STATUS_RANGE = "Current!B19:D19"
CURRENT_UTC_CELL = "Current!B6"
FLOOR_TRIAL_STATUS_RANGE = FLOOR_STATUS_RANGE
FLOOR_TRIAL_DATE_CELL = FLOOR_OPEN_RANGE
FLOOR_TRIAL_START_CELL = FLOOR_START_RANGE
FLOOR_TRIAL_END_CELL = FLOOR_END_RANGE

# Additional sheet/range constants (for backward compatibility)
SHEET_RANGE = f"{CURRENT_SHEET}!A:Z"
MONITOR_RANGE = f"{CURRENT_SHEET}!C6:C11"
HISTORY_SHEET_NAME = "History"
RAW_SUBMISSIONS_RANGE = "RawSubmissions!A4:G"
REPORT_RANGE = "Report!A4:E"
COMPACTION_RANGE = "Current!E6:I12"
AUTOMATION_CONTROL_CELL = "Current!H2"
PRIORITY_DIVISION_RANGE = "Current!F16:F30"
PRIORITY_FLAG_RANGE = "Current!G16:G30"
REJECTED_SUBMISSIONS_RANGE = "RejectedSubmissions!B:H"
EXTERNAL_SOURCE_RANGE = "Form Responses 1!A2:H"
